Bumping gaia.json for 3 gaia-1_2f revision(s) a=gaia-bump
========

https://hg.mozilla.org/integration/gaia-1_2f/rev/3ad4c22c31e8
Author: Dave Huseby <dhuseby@mozilla.com>
Desc: Bug 943313 - AttributeError: 'builtin_function_or_method' object has no attribute 'sleep' after adding power draw support. r=dhunt

========

https://hg.mozilla.org/integration/gaia-1_2f/rev/df751d978e54
Author: Rudy Lu <me@rudy.lu>
Desc: Merge pull request #13976 from aniruddha-adhikary/master

Bug 842592: Adding Bangla Input Method for B2G.
r=rudylu(cherry picked from commit 47161c8a657c25ee7b29c84ce3b4e4df191c09a0)
a=timdream

Conflicts:
	.jshintignore

========

https://hg.mozilla.org/integration/gaia-1_2f/rev/13812380215a
Author: Gabriele Svelto <gsvelto@mozilla.com>
Desc: Bug 932209 - Do not automatically close the app if there are pending messages waiting to be processed r=julienw